module.exports = {
  verbose: true,
  testEnvironment: 'node',
  testPathIgnorePatterns: [
    '/node_modules/',
    '/__seeders__/',
    '/__mocks__/',
    '/__fixtures__/',
    '/__helpers__/',
    '/config/',
    '/coverage/',
    '/public/',
    '/.vs/',
    '/.vscode/',
    '/.next/',
  ],
  testMatch: ['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[jt]s?(x)', '!**/*.cases.[jt]s?(x)'],
  globals: {},
  collectCoverage: false,
  collectCoverageFrom: [
    '**/*.{js,jsx}',
    '!**/jest.config.js',
    '!**/config.js',
    '!**/index.js',
    '!**/config/**',
    '!**/node_modules/**',
    '!**/__seeders__/**',
    '!**/__mocks__/**',
    '!**/__fixtures__/**',
    '!**/__helpers__/**',
    '!**/coverage/**',
    '!**/.vs/**',
    '!**/.vscode/**',
    '!**/.next/**',
  ],
  coverageReporters: ['text', 'text-summary'],
}
